### ISSUE TITLE
make Expat example to use vcpkg please

### ISSUE THREAD

**Issue by ghost** [kraken175/expat-example-cpp#1]
You compiled the example with **MinGW GCC** and you are pretty great,
but @kraken175  please add _CMakeLists.txt_ for vcpkg so it can be built with MSVC compilers.

Just do it or else the compilation won't be better with MinGW GCC Compilers!

**Comment by kraken175** [comment]
Alright, I'll add the _CMakeLists.txt_ to use vcpkg
