### ISSUE TITLE
NEWS: Increased Development And Code Quality With MSVC - No more MinGW Binaries

### ISSUE THREAD

**Issue by kraken175** [kraken175/expat-example-cpp#5]
I've uninstalled **MSYS2** because i don't want to use MinGW because of the _GNU Linker's code generation_. When using _gcc.exe_, generating code may be in bad quality and it's not gonna to stick with it!

At this time, we use MSVC and VCPKG to increase the Code Quality than MinGW. Then i link MSVC-Compiled libraries to make it high quality, and without .indent since MSVC does not support .indent's than MinGW's ones.
 
If you're new to C++ developers please remember:
- DON'T DOWNLOAD MINGW and CODEBLOCKS! Use this [link](https://visualstudio.microsoft.com/downloads/) to download the C++ Compiler, and the IDE. Just select "Desktop Development with C++" component, install the IDE and login into your account to Unlock IDE, or else use Developer Command Prompt.
- DON'T USE MSYS2 PACKAGE MANAGER! Use [vcpkg](https://github.com/microsoft/vcpkg/), it's our best shelf for your C++ libraries.
- DON'T USE THE GRAPHICS.H HEADER IN YOUR IDE! Since graphics.h was made for Borland C++, it's not gonna to run on 64bit OS because this is a 16-bit library! Just use some alternaties to graphics.h like: [Skia](https://github.com/google/skia) or [SFML](https://github.com/SFML/SFML)

**Comment by kraken175** [comment]
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 
@SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 @SFTCP1 

@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 
@iammopeio @iammopeio @iammopeio @iammopeio @iammopeio @iammopeio 

😔😔😔😔😔😔😔😔
😔😔😔😔😔😔 🩸😔
😔😔😔😔😔😔 🩸 🩸
😔😔😔😔😔😔😔😔
😔😔😔😔😔😔😔😔@LogoEditingMaster @LogoEditingMaster @LogoEditingMaster@ LogoEditingMaster
😔😔😔😔😔😔 🩸 🩸 🩸 🩸 🩸 🩸 🩸 🩸 🩸 🩸 @LogoEditingMaster @LogoEditingMaster@ LogoEditingMaster
😔😔😔😔😔😔😔😔@LogoEditingMaster@ LogoEditingMaster @LogoEditingMaster@ LogoEditingMaster
😔😔😔😔😔😔😔😔
          😔😔😔😔
          😔😔😔😔
          😔😔😔😔                          @bdb391a  @bdb391a  @bdb391a  @bdb391a
          😔😔😔😔                          @bdb391a  @bdb391a  @bdb391a  @bdb391a
          😔😔😔😔😔😔😔😔😔😔😔
          😔😔😔😔😔😔😔😔😔😔😔
          😔😔😔😔
          😔😔😔😔
          😔😔😔😔
          😔😔😔😔
          😔😔😔😔
          😔😔😔😔

**Comment by kraken175** [comment]
🥒?

🍏?

🌖?

🔥?

**Comment by kraken175** [comment]
@deepbabies @deepbabies @deepbabies @deepbabies
@bdb391a @bdb391a @bdb391a @bdb391a @bdb391a
@notsodeepbabies @notsodeepbabies @notsodeepbabies

**Comment by SFTCP1** [comment]
😂

Tried to emoji
